from PyQt6 import QtCore, QtGui, QtWidgets
from vista.WidgetJugador import WidgetJugador


# class WidgetEscalon(QtWidgets.QWidget):
        
#         def __init__(self):
#             #self.wd_escalon1 = QtWidgets.QWidget(parent=self.widget_escalera)
#             self.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed))
#             self.setMinimumSize(QtCore.QSize(920, 0))
#             self.setMaximumSize(QtCore.QSize(920, 70))
#             self.setStyleSheet("background-color: rgb(213, 213, 213);")
            
#             self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self)
#             self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
#             self.horizontalLayout_2.setObjectName("horizontalLayout_2")
#             self.ly_escalon1 = QtWidgets.QHBoxLayout()
#             self.ly_escalon1.setObjectName("ly_escalon1")
#             self.icono_escalon1 = QtWidgets.QLabel(parent=self)
#             self.icono_escalon1.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed))
#             self.icono_escalon1.setMaximumSize(QtCore.QSize(50, 50))
#             self.icono_escalon1.setPixmap(QtGui.QPixmap("vista/img/number-1-circle-svgrepo-com.png"))
#             self.icono_escalon1.setScaledContents(True)
#             self.icono_escalon1.setObjectName("icono_escalon1")
#             self.ly_escalon1.addWidget(self.icono_escalon1)
#             self.tematica_escalon1 = QtWidgets.QLabel(parent=self)
#             font = QtGui.QFont()
#             font.setFamily("Sitka")
#             font.setPointSize(18)
#             self.tematica_escalon1.setFont(font)
#             self.tematica_escalon1.setObjectName("tematica_escalon1")
#             self.ly_escalon1.addWidget(self.tematica_escalon1)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 673)
        MainWindow.setMaximumSize(QtCore.QSize(952, 673))

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.widget_escalera = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_escalera.setGeometry(QtCore.QRect(0, 20, 951, 621))
        self.widget_escalera.setObjectName("widget_escalera")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_escalera)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wd_escalon8 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.wd_escalon8.setSizePolicy(sizePolicy)
        self.wd_escalon8.setMinimumSize(QtCore.QSize(550, 60))
        self.wd_escalon8.setMaximumSize(QtCore.QSize(550, 70))
        self.wd_escalon8.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon8.setObjectName("wd_escalon8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.wd_escalon8)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ly_escalon8 = QtWidgets.QHBoxLayout()
        self.ly_escalon8.setObjectName("ly_escalon8")
        self.icono_escalon8 = QtWidgets.QLabel(parent=self.wd_escalon8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon8.sizePolicy().hasHeightForWidth())
        self.icono_escalon8.setSizePolicy(sizePolicy)
        self.icono_escalon8.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon8.setText("")
        self.icono_escalon8.setPixmap(QtGui.QPixmap("vista/img/number-8-circle-svgrepo-com.png"))
        self.icono_escalon8.setScaledContents(True)
        self.icono_escalon8.setObjectName("icono_escalon8")
        self.ly_escalon8.addWidget(self.icono_escalon8)
        self.tematica_escalon8 = QtWidgets.QLabel(parent=self.wd_escalon8)
        font_sitka18 = QtGui.QFont()
        font_sitka18.setFamily("Sitka")
        font_sitka18.setPointSize(18)
        self.tematica_escalon8.setFont(font_sitka18)
        self.tematica_escalon8.setObjectName("tematica_escalon8")
        self.ly_escalon8.addWidget(self.tematica_escalon8)
        self.horizontalLayout_9.addLayout(self.ly_escalon8)
        self.verticalLayout.addWidget(self.wd_escalon8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon7 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon7.sizePolicy().hasHeightForWidth())
        self.wd_escalon7.setSizePolicy(sizePolicy)
        self.wd_escalon7.setMinimumSize(QtCore.QSize(600, 60))
        self.wd_escalon7.setMaximumSize(QtCore.QSize(600, 70))
        self.wd_escalon7.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon7.setObjectName("wd_escalon7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.wd_escalon7)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ly_escalon7 = QtWidgets.QHBoxLayout()
        self.ly_escalon7.setObjectName("ly_escalon7")
        self.icono_escalon7 = QtWidgets.QLabel(parent=self.wd_escalon7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon7.sizePolicy().hasHeightForWidth())
        self.icono_escalon7.setSizePolicy(sizePolicy)
        self.icono_escalon7.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon7.setText("")
        self.icono_escalon7.setPixmap(QtGui.QPixmap("vista/img/number-7-circle-svgrepo-com.png"))
        self.icono_escalon7.setScaledContents(True)
        self.icono_escalon7.setObjectName("icono_escalon7")
        self.ly_escalon7.addWidget(self.icono_escalon7)
        self.tematica_escalon7 = QtWidgets.QLabel(parent=self.wd_escalon7)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon7.setFont(font)
        self.tematica_escalon7.setObjectName("tematica_escalon7")
        self.ly_escalon7.addWidget(self.tematica_escalon7)
        self.horizontalLayout_8.addLayout(self.ly_escalon7)
        self.verticalLayout.addWidget(self.wd_escalon7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon6 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon6.sizePolicy().hasHeightForWidth())
        self.wd_escalon6.setSizePolicy(sizePolicy)
        self.wd_escalon6.setMinimumSize(QtCore.QSize(650, 60))
        self.wd_escalon6.setMaximumSize(QtCore.QSize(650, 70))
        self.wd_escalon6.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon6.setObjectName("wd_escalon6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.wd_escalon6)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ly_escalon6 = QtWidgets.QHBoxLayout()
        self.ly_escalon6.setObjectName("ly_escalon6")
        self.icono_escalon6 = QtWidgets.QLabel(parent=self.wd_escalon6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon6.sizePolicy().hasHeightForWidth())
        self.icono_escalon6.setSizePolicy(sizePolicy)
        self.icono_escalon6.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon6.setText("")
        self.icono_escalon6.setPixmap(QtGui.QPixmap("vista/img/number-6-circle-svgrepo-com.png"))
        self.icono_escalon6.setScaledContents(True)
        self.icono_escalon6.setObjectName("icono_escalon6")
        self.ly_escalon6.addWidget(self.icono_escalon6)
        self.tematica_escalon6 = QtWidgets.QLabel(parent=self.wd_escalon6)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon6.setFont(font)
        self.tematica_escalon6.setObjectName("tematica_escalon6")
        self.ly_escalon6.addWidget(self.tematica_escalon6)
        self.horizontalLayout_7.addLayout(self.ly_escalon6)
        self.verticalLayout.addWidget(self.wd_escalon6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon5 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon5.sizePolicy().hasHeightForWidth())
        self.wd_escalon5.setSizePolicy(sizePolicy)
        self.wd_escalon5.setMinimumSize(QtCore.QSize(700, 60))
        self.wd_escalon5.setMaximumSize(QtCore.QSize(700, 70))
        self.wd_escalon5.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon5.setObjectName("wd_escalon5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wd_escalon5)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ly_escalon5 = QtWidgets.QHBoxLayout()
        self.ly_escalon5.setObjectName("ly_escalon5")
        self.icono_escalon5 = QtWidgets.QLabel(parent=self.wd_escalon5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon5.sizePolicy().hasHeightForWidth())
        self.icono_escalon5.setSizePolicy(sizePolicy)
        self.icono_escalon5.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon5.setText("")
        self.icono_escalon5.setPixmap(QtGui.QPixmap("vista/img/number-5-circle-svgrepo-com.png"))
        self.icono_escalon5.setScaledContents(True)
        self.icono_escalon5.setObjectName("icono_escalon5")
        self.ly_escalon5.addWidget(self.icono_escalon5)
        self.tematica_escalon5 = QtWidgets.QLabel(parent=self.wd_escalon5)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon5.setFont(font)
        self.tematica_escalon5.setObjectName("tematica_escalon5")
        self.ly_escalon5.addWidget(self.tematica_escalon5)
        self.horizontalLayout_6.addLayout(self.ly_escalon5)
        self.verticalLayout.addWidget(self.wd_escalon5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon4 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon4.sizePolicy().hasHeightForWidth())
        self.wd_escalon4.setSizePolicy(sizePolicy)
        self.wd_escalon4.setMinimumSize(QtCore.QSize(750, 60))
        self.wd_escalon4.setMaximumSize(QtCore.QSize(750, 70))
        self.wd_escalon4.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon4.setObjectName("wd_escalon4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wd_escalon4)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ly_escalon4 = QtWidgets.QHBoxLayout()
        self.ly_escalon4.setObjectName("ly_escalon4")
        self.icono_escalon4 = QtWidgets.QLabel(parent=self.wd_escalon4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon4.sizePolicy().hasHeightForWidth())
        self.icono_escalon4.setSizePolicy(sizePolicy)
        self.icono_escalon4.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon4.setText("")
        self.icono_escalon4.setPixmap(QtGui.QPixmap("vista/img/number-4-circle-svgrepo-com.png"))
        self.icono_escalon4.setScaledContents(True)
        self.icono_escalon4.setObjectName("icono_escalon4")
        self.ly_escalon4.addWidget(self.icono_escalon4)
        self.tematica_escalon4 = QtWidgets.QLabel(parent=self.wd_escalon4)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon4.setFont(font)
        self.tematica_escalon4.setObjectName("tematica_escalon4")
        self.ly_escalon4.addWidget(self.tematica_escalon4)
        self.horizontalLayout_5.addLayout(self.ly_escalon4)
        self.verticalLayout.addWidget(self.wd_escalon4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon3 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon3.sizePolicy().hasHeightForWidth())
        self.wd_escalon3.setSizePolicy(sizePolicy)
        self.wd_escalon3.setMinimumSize(QtCore.QSize(800, 60))
        self.wd_escalon3.setMaximumSize(QtCore.QSize(800, 70))
        self.wd_escalon3.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon3.setObjectName("wd_escalon3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wd_escalon3)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ly_escalon3 = QtWidgets.QHBoxLayout()
        self.ly_escalon3.setObjectName("ly_escalon3")
        self.icono_escalon3 = QtWidgets.QLabel(parent=self.wd_escalon3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon3.sizePolicy().hasHeightForWidth())
        self.icono_escalon3.setSizePolicy(sizePolicy)
        self.icono_escalon3.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon3.setText("")
        self.icono_escalon3.setPixmap(QtGui.QPixmap("vista/img/number-3-circle-svgrepo-com.png"))
        self.icono_escalon3.setScaledContents(True)
        self.icono_escalon3.setObjectName("icono_escalon3")
        self.ly_escalon3.addWidget(self.icono_escalon3)
        self.tematica_escalon3 = QtWidgets.QLabel(parent=self.wd_escalon3)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon3.setFont(font)
        self.tematica_escalon3.setObjectName("tematica_escalon3")
        self.ly_escalon3.addWidget(self.tematica_escalon3)
        self.horizontalLayout_4.addLayout(self.ly_escalon3)
        self.verticalLayout.addWidget(self.wd_escalon3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon2 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon2.sizePolicy().hasHeightForWidth())
        self.wd_escalon2.setSizePolicy(sizePolicy)
        self.wd_escalon2.setMinimumSize(QtCore.QSize(850, 70))
        self.wd_escalon2.setMaximumSize(QtCore.QSize(850, 70))
        self.wd_escalon2.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon2.setObjectName("wd_escalon2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wd_escalon2)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ly_escalon2 = QtWidgets.QHBoxLayout()
        self.ly_escalon2.setObjectName("ly_escalon2")
        self.icono_escalon2 = QtWidgets.QLabel(parent=self.wd_escalon2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon2.sizePolicy().hasHeightForWidth())
        self.icono_escalon2.setSizePolicy(sizePolicy)
        self.icono_escalon2.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon2.setText("")
        self.icono_escalon2.setPixmap(QtGui.QPixmap("vista/img/number-2-circle-svgrepo-com.png"))
        self.icono_escalon2.setScaledContents(True)
        self.icono_escalon2.setObjectName("icono_escalon2")
        self.ly_escalon2.addWidget(self.icono_escalon2)
        self.tematica_escalon2 = QtWidgets.QLabel(parent=self.wd_escalon2)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon2.setFont(font)
        self.tematica_escalon2.setObjectName("tematica_escalon2")
        self.ly_escalon2.addWidget(self.tematica_escalon2)
        self.horizontalLayout_3.addLayout(self.ly_escalon2)
        self.verticalLayout.addWidget(self.wd_escalon2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.wd_escalon1 = QtWidgets.QWidget(parent=self.widget_escalera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wd_escalon1.sizePolicy().hasHeightForWidth())
        self.wd_escalon1.setSizePolicy(sizePolicy)
        self.wd_escalon1.setMinimumSize(QtCore.QSize(920, 0))
        self.wd_escalon1.setMaximumSize(QtCore.QSize(920, 70))
        self.wd_escalon1.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.wd_escalon1.setObjectName("wd_escalon1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wd_escalon1)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ly_escalon1 = QtWidgets.QHBoxLayout()
        self.ly_escalon1.setObjectName("ly_escalon1")
        self.icono_escalon1 = QtWidgets.QLabel(parent=self.wd_escalon1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icono_escalon1.sizePolicy().hasHeightForWidth())
        self.icono_escalon1.setSizePolicy(sizePolicy)
        self.icono_escalon1.setMaximumSize(QtCore.QSize(50, 50))
        self.icono_escalon1.setText("")
        self.icono_escalon1.setPixmap(QtGui.QPixmap("vista/img/number-1-circle-svgrepo-com.png"))
        self.icono_escalon1.setScaledContents(True)
        self.icono_escalon1.setObjectName("icono_escalon1")
        self.ly_escalon1.addWidget(self.icono_escalon1)
        self.tematica_escalon1 = QtWidgets.QLabel(parent=self.wd_escalon1)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        self.tematica_escalon1.setFont(font)
        self.tematica_escalon1.setObjectName("tematica_escalon1")
        self.ly_escalon1.addWidget(self.tematica_escalon1)

        #JUGADORES
        self.wd_j1 = WidgetJugador(self.wd_escalon1, "Fiorella", "vista/img/fi.jpg", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j2 = WidgetJugador(self.wd_escalon1, "Tania", "vista/img/ta.png", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j3 = WidgetJugador(self.wd_escalon1, "Dayana", "vista/img/da.jpg", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j4 = WidgetJugador(self.wd_escalon1, "Carlos", "vista/img/edna.jpg", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j5 = WidgetJugador(self.wd_escalon1, "Bruno", "vista/img/avatar_azul.png", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j6 = WidgetJugador(self.wd_escalon1, "Alexis", "vista/img/al.jpg", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j7 = WidgetJugador(self.wd_escalon1, "Facundo", "vista/img/fa.jpg", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j8 = WidgetJugador(self.wd_escalon1, "Kadir", "vista/img/ka.jpg", "vista/img/vacio.png","vista/img/vacio.png")
        self.wd_j9 = WidgetJugador(self.wd_escalon1, "Ignacio", "vista/img/jarr.jpg", "vista/img/vacio.png","vista/img/vacio.png")

        self.ly_escalon1.addWidget(self.wd_j1)
        self.ly_escalon1.addWidget(self.wd_j2)
        self.ly_escalon1.addWidget(self.wd_j3)
        self.ly_escalon1.addWidget(self.wd_j4)
        self.ly_escalon1.addWidget(self.wd_j5)
        self.ly_escalon1.addWidget(self.wd_j6)
        self.ly_escalon1.addWidget(self.wd_j7)
        self.ly_escalon1.addWidget(self.wd_j8)
        self.ly_escalon1.addWidget(self.wd_j9)


        self.horizontalLayout_2.addLayout(self.ly_escalon1) #???????????
        self.verticalLayout.addWidget(self.wd_escalon1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout) #???????????
        self.gif = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(750, 10, 191, 81))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("../../Downloads/ganador-triunfador.gif"))
        self.gif.setScaledContents(True)
        self.gif.setWordWrap(False)
        self.gif.setObjectName("gif")
        self.pushButton_atras = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_atras.setGeometry(QtCore.QRect(20, 640, 75, 24))
        self.pushButton_atras.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.lista_nombres_escalon = [self.tematica_escalon1, self.tematica_escalon2, self.tematica_escalon3, self.tematica_escalon4, self.tematica_escalon5, self.tematica_escalon6, self.tematica_escalon7, self.tematica_escalon8 ]

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tematica_escalon8.setText(_translate("MainWindow", "-"))
        self.tematica_escalon7.setText(_translate("MainWindow", "-"))
        self.tematica_escalon6.setText(_translate("MainWindow", "-"))
        self.tematica_escalon5.setText(_translate("MainWindow", "-"))
        self.tematica_escalon4.setText(_translate("MainWindow", "-"))
        self.tematica_escalon3.setText(_translate("MainWindow", "-"))
        self.tematica_escalon2.setText(_translate("MainWindow", "-"))
        self.tematica_escalon1.setText(_translate("MainWindow", "-"))
        self.pushButton_atras.setText(_translate("MainWindow", "Atras"))


    def get_button_atras(self):
        return self.pushButton_atras

    def get_lista_nombres_escalon(self):
        return self.lista_nombres_escalon

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
