from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 531)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_56 = QtWidgets.QWidget(parent=self.widget)
        self.widget_56.setMaximumSize(QtCore.QSize(750, 60))
        self.widget_56.setStyleSheet("background-color: rgb(194, 174, 255);\n"
"")
        self.widget_56.setObjectName("widget_56")
        self.horizontalLayout_117 = QtWidgets.QHBoxLayout(self.widget_56)
        self.horizontalLayout_117.setObjectName("horizontalLayout_117")
        self.horizontalLayout_118 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_118.setObjectName("horizontalLayout_118")
        self.label_150 = QtWidgets.QLabel(parent=self.widget_56)
        self.label_150.setMaximumSize(QtCore.QSize(30, 30))
        self.label_150.setText("")
        self.label_150.setPixmap(QtGui.QPixmap("../../uno.png"))
        self.label_150.setScaledContents(True)
        self.label_150.setObjectName("label_150")
        self.horizontalLayout_118.addWidget(self.label_150, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_151 = QtWidgets.QLabel(parent=self.widget_56)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_151.setFont(font)
        self.label_151.setStyleSheet("letter-spacing : 10px;\n"
"font-weight: bold;\n"
"font-size: 25px;")
        self.label_151.setObjectName("label_151")
        self.horizontalLayout_118.addWidget(self.label_151, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_199 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_199.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_199.setStyleSheet("")
        self.widget_199.setObjectName("widget_199")
        self.verticalLayout_109 = QtWidgets.QVBoxLayout(self.widget_199)
        self.verticalLayout_109.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_109.setSpacing(0)
        self.verticalLayout_109.setObjectName("verticalLayout_109")
        self.label_152 = QtWidgets.QLabel(parent=self.widget_199)
        self.label_152.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_152.setFont(font)
        self.label_152.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_152.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_152.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_152.setWordWrap(False)
        self.label_152.setObjectName("label_152")
        self.verticalLayout_109.addWidget(self.label_152)
        self.widget_200 = QtWidgets.QWidget(parent=self.widget_199)
        self.widget_200.setObjectName("widget_200")
        self.gridLayout_91 = QtWidgets.QGridLayout(self.widget_200)
        self.gridLayout_91.setObjectName("gridLayout_91")
        self.horizontalLayout_119 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_119.setObjectName("horizontalLayout_119")
        self.checkBox_181 = QtWidgets.QCheckBox(parent=self.widget_200)
        self.checkBox_181.setEnabled(False)
        self.checkBox_181.setText("")
        self.checkBox_181.setCheckable(False)
        self.checkBox_181.setObjectName("checkBox_181")
        self.horizontalLayout_119.addWidget(self.checkBox_181, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_182 = QtWidgets.QCheckBox(parent=self.widget_200)
        self.checkBox_182.setEnabled(False)
        self.checkBox_182.setText("")
        self.checkBox_182.setCheckable(False)
        self.checkBox_182.setObjectName("checkBox_182")
        self.horizontalLayout_119.addWidget(self.checkBox_182, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_91.addLayout(self.horizontalLayout_119, 0, 0, 1, 1)
        self.verticalLayout_109.addWidget(self.widget_200)
        self.horizontalLayout_118.addWidget(self.widget_199)
        self.widget_201 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_201.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_201.setStyleSheet("")
        self.widget_201.setObjectName("widget_201")
        self.verticalLayout_110 = QtWidgets.QVBoxLayout(self.widget_201)
        self.verticalLayout_110.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_110.setSpacing(0)
        self.verticalLayout_110.setObjectName("verticalLayout_110")
        self.label_153 = QtWidgets.QLabel(parent=self.widget_201)
        self.label_153.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_153.setFont(font)
        self.label_153.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_153.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_153.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_153.setWordWrap(False)
        self.label_153.setObjectName("label_153")
        self.verticalLayout_110.addWidget(self.label_153)
        self.widget_202 = QtWidgets.QWidget(parent=self.widget_201)
        self.widget_202.setObjectName("widget_202")
        self.gridLayout_92 = QtWidgets.QGridLayout(self.widget_202)
        self.gridLayout_92.setObjectName("gridLayout_92")
        self.horizontalLayout_120 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_120.setObjectName("horizontalLayout_120")
        self.checkBox_183 = QtWidgets.QCheckBox(parent=self.widget_202)
        self.checkBox_183.setEnabled(False)
        self.checkBox_183.setText("")
        self.checkBox_183.setCheckable(False)
        self.checkBox_183.setObjectName("checkBox_183")
        self.horizontalLayout_120.addWidget(self.checkBox_183, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_184 = QtWidgets.QCheckBox(parent=self.widget_202)
        self.checkBox_184.setEnabled(False)
        self.checkBox_184.setText("")
        self.checkBox_184.setCheckable(False)
        self.checkBox_184.setObjectName("checkBox_184")
        self.horizontalLayout_120.addWidget(self.checkBox_184, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_92.addLayout(self.horizontalLayout_120, 0, 0, 1, 1)
        self.verticalLayout_110.addWidget(self.widget_202)
        self.horizontalLayout_118.addWidget(self.widget_201)
        self.widget_203 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_203.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_203.setStyleSheet("")
        self.widget_203.setObjectName("widget_203")
        self.verticalLayout_111 = QtWidgets.QVBoxLayout(self.widget_203)
        self.verticalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_111.setSpacing(0)
        self.verticalLayout_111.setObjectName("verticalLayout_111")
        self.label_154 = QtWidgets.QLabel(parent=self.widget_203)
        self.label_154.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_154.setFont(font)
        self.label_154.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_154.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_154.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_154.setWordWrap(False)
        self.label_154.setObjectName("label_154")
        self.verticalLayout_111.addWidget(self.label_154)
        self.widget_204 = QtWidgets.QWidget(parent=self.widget_203)
        self.widget_204.setObjectName("widget_204")
        self.gridLayout_93 = QtWidgets.QGridLayout(self.widget_204)
        self.gridLayout_93.setObjectName("gridLayout_93")
        self.horizontalLayout_121 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_121.setObjectName("horizontalLayout_121")
        self.checkBox_185 = QtWidgets.QCheckBox(parent=self.widget_204)
        self.checkBox_185.setEnabled(False)
        self.checkBox_185.setText("")
        self.checkBox_185.setCheckable(False)
        self.checkBox_185.setObjectName("checkBox_185")
        self.horizontalLayout_121.addWidget(self.checkBox_185, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_186 = QtWidgets.QCheckBox(parent=self.widget_204)
        self.checkBox_186.setEnabled(False)
        self.checkBox_186.setText("")
        self.checkBox_186.setCheckable(False)
        self.checkBox_186.setObjectName("checkBox_186")
        self.horizontalLayout_121.addWidget(self.checkBox_186, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_93.addLayout(self.horizontalLayout_121, 0, 0, 1, 1)
        self.verticalLayout_111.addWidget(self.widget_204)
        self.horizontalLayout_118.addWidget(self.widget_203)
        self.widget_205 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_205.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_205.setStyleSheet("")
        self.widget_205.setObjectName("widget_205")
        self.verticalLayout_112 = QtWidgets.QVBoxLayout(self.widget_205)
        self.verticalLayout_112.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_112.setSpacing(0)
        self.verticalLayout_112.setObjectName("verticalLayout_112")
        self.label_155 = QtWidgets.QLabel(parent=self.widget_205)
        self.label_155.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_155.setFont(font)
        self.label_155.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_155.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_155.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_155.setWordWrap(False)
        self.label_155.setObjectName("label_155")
        self.verticalLayout_112.addWidget(self.label_155)
        self.widget_206 = QtWidgets.QWidget(parent=self.widget_205)
        self.widget_206.setObjectName("widget_206")
        self.gridLayout_94 = QtWidgets.QGridLayout(self.widget_206)
        self.gridLayout_94.setObjectName("gridLayout_94")
        self.horizontalLayout_122 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_122.setObjectName("horizontalLayout_122")
        self.checkBox_187 = QtWidgets.QCheckBox(parent=self.widget_206)
        self.checkBox_187.setEnabled(False)
        self.checkBox_187.setText("")
        self.checkBox_187.setCheckable(False)
        self.checkBox_187.setObjectName("checkBox_187")
        self.horizontalLayout_122.addWidget(self.checkBox_187, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_188 = QtWidgets.QCheckBox(parent=self.widget_206)
        self.checkBox_188.setEnabled(False)
        self.checkBox_188.setText("")
        self.checkBox_188.setCheckable(False)
        self.checkBox_188.setObjectName("checkBox_188")
        self.horizontalLayout_122.addWidget(self.checkBox_188, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_94.addLayout(self.horizontalLayout_122, 0, 0, 1, 1)
        self.verticalLayout_112.addWidget(self.widget_206)
        self.horizontalLayout_118.addWidget(self.widget_205)
        self.widget_207 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_207.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_207.setStyleSheet("")
        self.widget_207.setObjectName("widget_207")
        self.verticalLayout_113 = QtWidgets.QVBoxLayout(self.widget_207)
        self.verticalLayout_113.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_113.setSpacing(0)
        self.verticalLayout_113.setObjectName("verticalLayout_113")
        self.label_156 = QtWidgets.QLabel(parent=self.widget_207)
        self.label_156.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_156.setFont(font)
        self.label_156.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_156.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_156.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_156.setWordWrap(False)
        self.label_156.setObjectName("label_156")
        self.verticalLayout_113.addWidget(self.label_156)
        self.widget_208 = QtWidgets.QWidget(parent=self.widget_207)
        self.widget_208.setObjectName("widget_208")
        self.gridLayout_95 = QtWidgets.QGridLayout(self.widget_208)
        self.gridLayout_95.setObjectName("gridLayout_95")
        self.horizontalLayout_123 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_123.setObjectName("horizontalLayout_123")
        self.checkBox_189 = QtWidgets.QCheckBox(parent=self.widget_208)
        self.checkBox_189.setEnabled(False)
        self.checkBox_189.setText("")
        self.checkBox_189.setCheckable(False)
        self.checkBox_189.setObjectName("checkBox_189")
        self.horizontalLayout_123.addWidget(self.checkBox_189, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_190 = QtWidgets.QCheckBox(parent=self.widget_208)
        self.checkBox_190.setEnabled(False)
        self.checkBox_190.setText("")
        self.checkBox_190.setCheckable(False)
        self.checkBox_190.setObjectName("checkBox_190")
        self.horizontalLayout_123.addWidget(self.checkBox_190, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_95.addLayout(self.horizontalLayout_123, 0, 0, 1, 1)
        self.verticalLayout_113.addWidget(self.widget_208)
        self.horizontalLayout_118.addWidget(self.widget_207)
        self.widget_209 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_209.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_209.setStyleSheet("")
        self.widget_209.setObjectName("widget_209")
        self.verticalLayout_114 = QtWidgets.QVBoxLayout(self.widget_209)
        self.verticalLayout_114.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_114.setSpacing(0)
        self.verticalLayout_114.setObjectName("verticalLayout_114")
        self.label_157 = QtWidgets.QLabel(parent=self.widget_209)
        self.label_157.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_157.setFont(font)
        self.label_157.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_157.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_157.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_157.setWordWrap(False)
        self.label_157.setObjectName("label_157")
        self.verticalLayout_114.addWidget(self.label_157)
        self.widget_210 = QtWidgets.QWidget(parent=self.widget_209)
        self.widget_210.setObjectName("widget_210")
        self.gridLayout_96 = QtWidgets.QGridLayout(self.widget_210)
        self.gridLayout_96.setObjectName("gridLayout_96")
        self.horizontalLayout_124 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_124.setObjectName("horizontalLayout_124")
        self.checkBox_191 = QtWidgets.QCheckBox(parent=self.widget_210)
        self.checkBox_191.setEnabled(False)
        self.checkBox_191.setText("")
        self.checkBox_191.setCheckable(False)
        self.checkBox_191.setObjectName("checkBox_191")
        self.horizontalLayout_124.addWidget(self.checkBox_191, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_192 = QtWidgets.QCheckBox(parent=self.widget_210)
        self.checkBox_192.setEnabled(False)
        self.checkBox_192.setText("")
        self.checkBox_192.setCheckable(False)
        self.checkBox_192.setObjectName("checkBox_192")
        self.horizontalLayout_124.addWidget(self.checkBox_192, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_96.addLayout(self.horizontalLayout_124, 0, 0, 1, 1)
        self.verticalLayout_114.addWidget(self.widget_210)
        self.horizontalLayout_118.addWidget(self.widget_209)
        self.widget_211 = QtWidgets.QWidget(parent=self.widget_56)
        self.widget_211.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_211.setStyleSheet("")
        self.widget_211.setObjectName("widget_211")
        self.verticalLayout_115 = QtWidgets.QVBoxLayout(self.widget_211)
        self.verticalLayout_115.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_115.setSpacing(0)
        self.verticalLayout_115.setObjectName("verticalLayout_115")
        self.label_158 = QtWidgets.QLabel(parent=self.widget_211)
        self.label_158.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_158.setFont(font)
        self.label_158.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_158.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_158.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_158.setWordWrap(False)
        self.label_158.setObjectName("label_158")
        self.verticalLayout_115.addWidget(self.label_158)
        self.widget_212 = QtWidgets.QWidget(parent=self.widget_211)
        self.widget_212.setObjectName("widget_212")
        self.gridLayout_97 = QtWidgets.QGridLayout(self.widget_212)
        self.gridLayout_97.setObjectName("gridLayout_97")
        self.horizontalLayout_125 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_125.setObjectName("horizontalLayout_125")
        self.checkBox_193 = QtWidgets.QCheckBox(parent=self.widget_212)
        self.checkBox_193.setEnabled(False)
        self.checkBox_193.setText("")
        self.checkBox_193.setCheckable(False)
        self.checkBox_193.setObjectName("checkBox_193")
        self.horizontalLayout_125.addWidget(self.checkBox_193, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_194 = QtWidgets.QCheckBox(parent=self.widget_212)
        self.checkBox_194.setEnabled(False)
        self.checkBox_194.setText("")
        self.checkBox_194.setCheckable(False)
        self.checkBox_194.setObjectName("checkBox_194")
        self.horizontalLayout_125.addWidget(self.checkBox_194, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_97.addLayout(self.horizontalLayout_125, 0, 0, 1, 1)
        self.verticalLayout_115.addWidget(self.widget_212)
        self.horizontalLayout_118.addWidget(self.widget_211)
        self.horizontalLayout_117.addLayout(self.horizontalLayout_118)
        self.verticalLayout.addWidget(self.widget_56, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_39 = QtWidgets.QWidget(parent=self.widget)
        self.widget_39.setMaximumSize(QtCore.QSize(750, 60))
        self.widget_39.setStyleSheet("background-color: rgb(194, 174, 255);\n"
"")
        self.widget_39.setObjectName("widget_39")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_39)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_39)
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../uno.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_22.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_39)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("letter-spacing : 10px;\n"
"font-weight: bold;\n"
"font-size: 25px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_22.addWidget(self.label_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_40 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_40.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_40.setStyleSheet("")
        self.widget_40.setObjectName("widget_40")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_40)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_61 = QtWidgets.QLabel(parent=self.widget_40)
        self.label_61.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_61.setFont(font)
        self.label_61.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_61.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_61.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_61.setWordWrap(False)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_30.addWidget(self.label_61)
        self.widget_41 = QtWidgets.QWidget(parent=self.widget_40)
        self.widget_41.setObjectName("widget_41")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_41)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_23 = QtWidgets.QCheckBox(parent=self.widget_41)
        self.checkBox_23.setEnabled(False)
        self.checkBox_23.setText("")
        self.checkBox_23.setCheckable(False)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_23.addWidget(self.checkBox_23, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_24 = QtWidgets.QCheckBox(parent=self.widget_41)
        self.checkBox_24.setEnabled(False)
        self.checkBox_24.setText("")
        self.checkBox_24.setCheckable(False)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_23.addWidget(self.checkBox_24, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_12.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_30.addWidget(self.widget_41)
        self.horizontalLayout_22.addWidget(self.widget_40)
        self.widget_42 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_42.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_42.setStyleSheet("")
        self.widget_42.setObjectName("widget_42")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.widget_42)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_33 = QtWidgets.QLabel(parent=self.widget_42)
        self.label_33.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_33.setFont(font)
        self.label_33.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_33.setWordWrap(False)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_31.addWidget(self.label_33)
        self.widget_43 = QtWidgets.QWidget(parent=self.widget_42)
        self.widget_43.setObjectName("widget_43")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_43)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.checkBox_25 = QtWidgets.QCheckBox(parent=self.widget_43)
        self.checkBox_25.setEnabled(False)
        self.checkBox_25.setText("")
        self.checkBox_25.setCheckable(False)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_24.addWidget(self.checkBox_25, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_26 = QtWidgets.QCheckBox(parent=self.widget_43)
        self.checkBox_26.setEnabled(False)
        self.checkBox_26.setText("")
        self.checkBox_26.setCheckable(False)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_24.addWidget(self.checkBox_26, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_13.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.verticalLayout_31.addWidget(self.widget_43)
        self.horizontalLayout_22.addWidget(self.widget_42)
        self.widget_44 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_44.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_44.setStyleSheet("")
        self.widget_44.setObjectName("widget_44")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.widget_44)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_31 = QtWidgets.QLabel(parent=self.widget_44)
        self.label_31.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_31.setFont(font)
        self.label_31.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setWordWrap(False)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_32.addWidget(self.label_31)
        self.widget_45 = QtWidgets.QWidget(parent=self.widget_44)
        self.widget_45.setObjectName("widget_45")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_45)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkBox_27 = QtWidgets.QCheckBox(parent=self.widget_45)
        self.checkBox_27.setEnabled(False)
        self.checkBox_27.setText("")
        self.checkBox_27.setCheckable(False)
        self.checkBox_27.setObjectName("checkBox_27")
        self.horizontalLayout_25.addWidget(self.checkBox_27, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_28 = QtWidgets.QCheckBox(parent=self.widget_45)
        self.checkBox_28.setEnabled(False)
        self.checkBox_28.setText("")
        self.checkBox_28.setCheckable(False)
        self.checkBox_28.setObjectName("checkBox_28")
        self.horizontalLayout_25.addWidget(self.checkBox_28, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_14.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.verticalLayout_32.addWidget(self.widget_45)
        self.horizontalLayout_22.addWidget(self.widget_44)
        self.widget_46 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_46.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_46.setStyleSheet("")
        self.widget_46.setObjectName("widget_46")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.widget_46)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_46)
        self.label_29.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setWordWrap(False)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_33.addWidget(self.label_29)
        self.widget_47 = QtWidgets.QWidget(parent=self.widget_46)
        self.widget_47.setObjectName("widget_47")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_47)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.checkBox_29 = QtWidgets.QCheckBox(parent=self.widget_47)
        self.checkBox_29.setEnabled(False)
        self.checkBox_29.setText("")
        self.checkBox_29.setCheckable(False)
        self.checkBox_29.setObjectName("checkBox_29")
        self.horizontalLayout_26.addWidget(self.checkBox_29, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_30 = QtWidgets.QCheckBox(parent=self.widget_47)
        self.checkBox_30.setEnabled(False)
        self.checkBox_30.setText("")
        self.checkBox_30.setCheckable(False)
        self.checkBox_30.setObjectName("checkBox_30")
        self.horizontalLayout_26.addWidget(self.checkBox_30, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_15.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.verticalLayout_33.addWidget(self.widget_47)
        self.horizontalLayout_22.addWidget(self.widget_46)
        self.widget_48 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_48.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_48.setStyleSheet("")
        self.widget_48.setObjectName("widget_48")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.widget_48)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_48)
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_34.addWidget(self.label_13)
        self.widget_49 = QtWidgets.QWidget(parent=self.widget_48)
        self.widget_49.setObjectName("widget_49")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_49)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.checkBox_31 = QtWidgets.QCheckBox(parent=self.widget_49)
        self.checkBox_31.setEnabled(False)
        self.checkBox_31.setText("")
        self.checkBox_31.setCheckable(False)
        self.checkBox_31.setObjectName("checkBox_31")
        self.horizontalLayout_27.addWidget(self.checkBox_31, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_32 = QtWidgets.QCheckBox(parent=self.widget_49)
        self.checkBox_32.setEnabled(False)
        self.checkBox_32.setText("")
        self.checkBox_32.setCheckable(False)
        self.checkBox_32.setObjectName("checkBox_32")
        self.horizontalLayout_27.addWidget(self.checkBox_32, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_16.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.verticalLayout_34.addWidget(self.widget_49)
        self.horizontalLayout_22.addWidget(self.widget_48)
        self.widget_50 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_50.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_50.setStyleSheet("")
        self.widget_50.setObjectName("widget_50")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.widget_50)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_50)
        self.label_11.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_35.addWidget(self.label_11)
        self.widget_51 = QtWidgets.QWidget(parent=self.widget_50)
        self.widget_51.setObjectName("widget_51")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_51)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.checkBox_33 = QtWidgets.QCheckBox(parent=self.widget_51)
        self.checkBox_33.setEnabled(False)
        self.checkBox_33.setText("")
        self.checkBox_33.setCheckable(False)
        self.checkBox_33.setObjectName("checkBox_33")
        self.horizontalLayout_28.addWidget(self.checkBox_33, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_34 = QtWidgets.QCheckBox(parent=self.widget_51)
        self.checkBox_34.setEnabled(False)
        self.checkBox_34.setText("")
        self.checkBox_34.setCheckable(False)
        self.checkBox_34.setObjectName("checkBox_34")
        self.horizontalLayout_28.addWidget(self.checkBox_34, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_17.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.verticalLayout_35.addWidget(self.widget_51)
        self.horizontalLayout_22.addWidget(self.widget_50)
        self.widget_52 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_52.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_52.setStyleSheet("")
        self.widget_52.setObjectName("widget_52")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.widget_52)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_52)
        self.label_9.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_36.addWidget(self.label_9)
        self.widget_53 = QtWidgets.QWidget(parent=self.widget_52)
        self.widget_53.setObjectName("widget_53")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_53)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.checkBox_35 = QtWidgets.QCheckBox(parent=self.widget_53)
        self.checkBox_35.setEnabled(False)
        self.checkBox_35.setText("")
        self.checkBox_35.setCheckable(False)
        self.checkBox_35.setObjectName("checkBox_35")
        self.horizontalLayout_29.addWidget(self.checkBox_35, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_36 = QtWidgets.QCheckBox(parent=self.widget_53)
        self.checkBox_36.setEnabled(False)
        self.checkBox_36.setText("")
        self.checkBox_36.setCheckable(False)
        self.checkBox_36.setObjectName("checkBox_36")
        self.horizontalLayout_29.addWidget(self.checkBox_36, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_18.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.verticalLayout_36.addWidget(self.widget_53)
        self.horizontalLayout_22.addWidget(self.widget_52)
        self.widget_54 = QtWidgets.QWidget(parent=self.widget_39)
        self.widget_54.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_54.setStyleSheet("")
        self.widget_54.setObjectName("widget_54")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.widget_54)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_62 = QtWidgets.QLabel(parent=self.widget_54)
        self.label_62.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_62.setFont(font)
        self.label_62.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_62.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_62.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_62.setWordWrap(False)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_37.addWidget(self.label_62)
        self.widget_55 = QtWidgets.QWidget(parent=self.widget_54)
        self.widget_55.setObjectName("widget_55")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget_55)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.checkBox_37 = QtWidgets.QCheckBox(parent=self.widget_55)
        self.checkBox_37.setEnabled(False)
        self.checkBox_37.setText("")
        self.checkBox_37.setCheckable(False)
        self.checkBox_37.setObjectName("checkBox_37")
        self.horizontalLayout_30.addWidget(self.checkBox_37, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_38 = QtWidgets.QCheckBox(parent=self.widget_55)
        self.checkBox_38.setEnabled(False)
        self.checkBox_38.setText("")
        self.checkBox_38.setCheckable(False)
        self.checkBox_38.setObjectName("checkBox_38")
        self.horizontalLayout_30.addWidget(self.checkBox_38, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_19.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.verticalLayout_37.addWidget(self.widget_55)
        self.horizontalLayout_22.addWidget(self.widget_54)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.verticalLayout.addWidget(self.widget_39, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(800, 60))
        self.widget_2.setStyleSheet("background-color: rgb(194, 174, 255);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../uno.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("letter-spacing : 10px;\n"
"font-weight: bold;\n"
"font-size: 25px;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_17.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_17.setStyleSheet("")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_34 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_34.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_34.setFont(font)
        self.label_34.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_34.setWordWrap(False)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_17.addWidget(self.label_34)
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_17)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.widget_9)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setText("")
        self.checkBox_2.setCheckable(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_10.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(parent=self.widget_9)
        self.checkBox.setEnabled(False)
        self.checkBox.setText("")
        self.checkBox.setCheckable(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_10.addWidget(self.checkBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.widget_9)
        self.horizontalLayout.addWidget(self.widget_17)
        self.widget_16 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_16.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_16.setStyleSheet("")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_32 = QtWidgets.QLabel(parent=self.widget_16)
        self.label_32.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_32.setFont(font)
        self.label_32.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setWordWrap(False)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_16.addWidget(self.label_32)
        self.widget_31 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_31.setObjectName("widget_31")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_31)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.widget_31)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setText("")
        self.checkBox_5.setCheckable(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_12.addWidget(self.checkBox_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.widget_31)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setText("")
        self.checkBox_6.setCheckable(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_12.addWidget(self.checkBox_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.widget_31)
        self.horizontalLayout.addWidget(self.widget_16)
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_15.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_15.setStyleSheet("")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_15)
        self.label_30.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_30.setFont(font)
        self.label_30.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setWordWrap(False)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_15.addWidget(self.label_30)
        self.widget_32 = QtWidgets.QWidget(parent=self.widget_15)
        self.widget_32.setObjectName("widget_32")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_32)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.widget_32)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setText("")
        self.checkBox_7.setCheckable(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_13.addWidget(self.checkBox_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self.widget_32)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setText("")
        self.checkBox_8.setCheckable(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_13.addWidget(self.checkBox_8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.widget_32)
        self.horizontalLayout.addWidget(self.widget_15)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_8.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_14.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.widget_33 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_33.setObjectName("widget_33")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_33)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_11 = QtWidgets.QCheckBox(parent=self.widget_33)
        self.checkBox_11.setEnabled(False)
        self.checkBox_11.setText("")
        self.checkBox_11.setCheckable(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_15.addWidget(self.checkBox_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_12 = QtWidgets.QCheckBox(parent=self.widget_33)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setText("")
        self.checkBox_12.setCheckable(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_15.addWidget(self.checkBox_12, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_33)
        self.horizontalLayout.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_7.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_12.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.widget_34 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_34.setObjectName("widget_34")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_34)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox_13 = QtWidgets.QCheckBox(parent=self.widget_34)
        self.checkBox_13.setEnabled(False)
        self.checkBox_13.setText("")
        self.checkBox_13.setCheckable(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_16.addWidget(self.checkBox_13, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_14 = QtWidgets.QCheckBox(parent=self.widget_34)
        self.checkBox_14.setEnabled(False)
        self.checkBox_14.setText("")
        self.checkBox_14.setCheckable(False)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_16.addWidget(self.checkBox_14, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_7.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_34)
        self.horizontalLayout.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_6.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_10.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.widget_35 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_35.setObjectName("widget_35")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_35)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBox_15 = QtWidgets.QCheckBox(parent=self.widget_35)
        self.checkBox_15.setEnabled(False)
        self.checkBox_15.setText("")
        self.checkBox_15.setCheckable(False)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_17.addWidget(self.checkBox_15, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_16 = QtWidgets.QCheckBox(parent=self.widget_35)
        self.checkBox_16.setEnabled(False)
        self.checkBox_16.setText("")
        self.checkBox_16.setCheckable(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_17.addWidget(self.checkBox_16, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_8.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.widget_35)
        self.horizontalLayout.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_8.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.widget_36 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_36.setObjectName("widget_36")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_36)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkBox_17 = QtWidgets.QCheckBox(parent=self.widget_36)
        self.checkBox_17.setEnabled(False)
        self.checkBox_17.setText("")
        self.checkBox_17.setCheckable(False)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_18.addWidget(self.checkBox_17, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_18 = QtWidgets.QCheckBox(parent=self.widget_36)
        self.checkBox_18.setEnabled(False)
        self.checkBox_18.setText("")
        self.checkBox_18.setCheckable(False)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_18.addWidget(self.checkBox_18, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_36)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_6.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.widget_37 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_37.setObjectName("widget_37")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_37)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.checkBox_19 = QtWidgets.QCheckBox(parent=self.widget_37)
        self.checkBox_19.setEnabled(False)
        self.checkBox_19.setText("")
        self.checkBox_19.setCheckable(False)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_19.addWidget(self.checkBox_19, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_20 = QtWidgets.QCheckBox(parent=self.widget_37)
        self.checkBox_20.setEnabled(False)
        self.checkBox_20.setText("")
        self.checkBox_20.setCheckable(False)
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout_19.addWidget(self.checkBox_20, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_10.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_37)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(50, 60))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_2.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.widget_38 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_38.setObjectName("widget_38")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_38)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_21 = QtWidgets.QCheckBox(parent=self.widget_38)
        self.checkBox_21.setEnabled(False)
        self.checkBox_21.setText("")
        self.checkBox_21.setCheckable(False)
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_20.addWidget(self.checkBox_21, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox_22 = QtWidgets.QCheckBox(parent=self.widget_38)
        self.checkBox_22.setEnabled(False)
        self.checkBox_22.setText("")
        self.checkBox_22.setCheckable(False)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_20.addWidget(self.checkBox_22, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_11.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_38)
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget_2)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_151.setText(_translate("MainWindow", "HISTORIA"))
        self.label_152.setText(_translate("MainWindow", "Jugador 1"))
        self.label_153.setText(_translate("MainWindow", "Jugador 2"))
        self.label_154.setText(_translate("MainWindow", "Jugador 3"))
        self.label_155.setText(_translate("MainWindow", "Jugador 4"))
        self.label_156.setText(_translate("MainWindow", "Jugador 5"))
        self.label_157.setText(_translate("MainWindow", "Jugador 6"))
        self.label_158.setText(_translate("MainWindow", "Jugador 7"))
        self.label_7.setText(_translate("MainWindow", "HISTORIA"))
        self.label_61.setText(_translate("MainWindow", "Jugador 1"))
        self.label_33.setText(_translate("MainWindow", "Jugador 2"))
        self.label_31.setText(_translate("MainWindow", "Jugador 3"))
        self.label_29.setText(_translate("MainWindow", "Jugador 4"))
        self.label_13.setText(_translate("MainWindow", "Jugador 5"))
        self.label_11.setText(_translate("MainWindow", "Jugador 6"))
        self.label_9.setText(_translate("MainWindow", "Jugador 7"))
        self.label_62.setText(_translate("MainWindow", "Jugador 8"))
        self.label_4.setText(_translate("MainWindow", "HISTORIA"))
        self.label_34.setText(_translate("MainWindow", "Jugador 1"))
        self.label_32.setText(_translate("MainWindow", "Jugador 2"))
        self.label_30.setText(_translate("MainWindow", "Jugador 3"))
        self.label_14.setText(_translate("MainWindow", "Jugador 4"))
        self.label_12.setText(_translate("MainWindow", "Jugador 5"))
        self.label_10.setText(_translate("MainWindow", "Jugador 6"))
        self.label_8.setText(_translate("MainWindow", "Jugador 7"))
        self.label_6.setText(_translate("MainWindow", "Jugador 8"))
        self.label_2.setText(_translate("MainWindow", "Jugador 9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
