from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(231, -1, 231, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_16 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem2)
        self.label_57 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_57.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_25.addWidget(self.label_57)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem3)
        self.pushButton_115 = QtWidgets.QPushButton(parent=self.frame_16)
        self.pushButton_115.setObjectName("pushButton_115")
        self.verticalLayout_25.addWidget(self.pushButton_115)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem4)
        self.pushButton_116 = QtWidgets.QPushButton(parent=self.frame_16)
        self.pushButton_116.setObjectName("pushButton_116")
        self.verticalLayout_25.addWidget(self.pushButton_116)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem5)
        self.gridLayout.addWidget(self.frame_16, 1, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.label_56 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_56.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_9.addWidget(self.label_56)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.pushButton_113 = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushButton_113.setObjectName("pushButton_113")
        self.verticalLayout_9.addWidget(self.pushButton_113)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.pushButton_114 = QtWidgets.QPushButton(parent=self.frame_15)
        self.pushButton_114.setObjectName("pushButton_114")
        self.verticalLayout_9.addWidget(self.pushButton_114)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.gridLayout.addWidget(self.frame_15, 2, 1, 1, 1)
        self.frame_12 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.label_53 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_53.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_4.addWidget(self.label_53)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.pushButton_107 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_107.setObjectName("pushButton_107")
        self.verticalLayout_4.addWidget(self.pushButton_107)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.pushButton_108 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_108.setObjectName("pushButton_108")
        self.verticalLayout_4.addWidget(self.pushButton_108)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.gridLayout.addWidget(self.frame_12, 0, 1, 1, 1)
        self.frame_14 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem14)
        self.label_55 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_55.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_8.addWidget(self.label_55)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem15)
        self.pushButton_111 = QtWidgets.QPushButton(parent=self.frame_14)
        self.pushButton_111.setObjectName("pushButton_111")
        self.verticalLayout_8.addWidget(self.pushButton_111)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.pushButton_112 = QtWidgets.QPushButton(parent=self.frame_14)
        self.pushButton_112.setObjectName("pushButton_112")
        self.verticalLayout_8.addWidget(self.pushButton_112)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.gridLayout.addWidget(self.frame_14, 1, 1, 1, 1)
        self.frame_17 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_26.addItem(spacerItem18)
        self.label_58 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_58.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_26.addWidget(self.label_58)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_26.addItem(spacerItem19)
        self.pushButton_117 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_117.setObjectName("pushButton_117")
        self.verticalLayout_26.addWidget(self.pushButton_117)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_26.addItem(spacerItem20)
        self.pushButton_118 = QtWidgets.QPushButton(parent=self.frame_17)
        self.pushButton_118.setObjectName("pushButton_118")
        self.verticalLayout_26.addWidget(self.pushButton_118)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_26.addItem(spacerItem21)
        self.gridLayout.addWidget(self.frame_17, 1, 2, 1, 1)
        self.frame_18 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem22)
        self.label_59 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_59.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_29.addWidget(self.label_59)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem23)
        self.pushButton_119 = QtWidgets.QPushButton(parent=self.frame_18)
        self.pushButton_119.setObjectName("pushButton_119")
        self.verticalLayout_29.addWidget(self.pushButton_119)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem24)
        self.pushButton_120 = QtWidgets.QPushButton(parent=self.frame_18)
        self.pushButton_120.setObjectName("pushButton_120")
        self.verticalLayout_29.addWidget(self.pushButton_120)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem25)
        self.gridLayout.addWidget(self.frame_18, 2, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_30.addItem(spacerItem26)
        self.label_60 = QtWidgets.QLabel(parent=self.frame_19)
        self.label_60.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_30.addWidget(self.label_60)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_30.addItem(spacerItem27)
        self.pushButton_121 = QtWidgets.QPushButton(parent=self.frame_19)
        self.pushButton_121.setObjectName("pushButton_121")
        self.verticalLayout_30.addWidget(self.pushButton_121)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_30.addItem(spacerItem28)
        self.pushButton_122 = QtWidgets.QPushButton(parent=self.frame_19)
        self.pushButton_122.setObjectName("pushButton_122")
        self.verticalLayout_30.addWidget(self.pushButton_122)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_30.addItem(spacerItem29)
        self.gridLayout.addWidget(self.frame_19, 2, 2, 1, 1)
        self.frame_11 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem30)
        self.label_52 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_52.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_3.addWidget(self.label_52)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem31)
        self.pushButton_105 = QtWidgets.QPushButton(parent=self.frame_11)
        self.pushButton_105.setObjectName("pushButton_105")
        self.verticalLayout_3.addWidget(self.pushButton_105)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem32)
        self.pushButton_106 = QtWidgets.QPushButton(parent=self.frame_11)
        self.pushButton_106.setObjectName("pushButton_106")
        self.verticalLayout_3.addWidget(self.pushButton_106)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem33)
        self.gridLayout.addWidget(self.frame_11, 0, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem34)
        self.label_54 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_54.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_7.addWidget(self.label_54)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem35)
        self.pushButton_109 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_109.setObjectName("pushButton_109")
        self.verticalLayout_7.addWidget(self.pushButton_109)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem36)
        self.pushButton_110 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_110.setObjectName("pushButton_110")
        self.verticalLayout_7.addWidget(self.pushButton_110)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem37)
        self.gridLayout.addWidget(self.frame_13, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem38)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Jugadores"))
        self.label_57.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_115.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_116.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_56.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_113.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_114.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_53.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_107.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_108.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_55.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_111.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_112.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_58.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_117.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_118.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_59.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_119.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_120.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_60.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_121.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_122.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_52.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_105.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_106.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.label_54.setText(_translate("MainWindow", "Jugador 1"))
        self.pushButton_109.setText(_translate("MainWindow", "Seleccionar Jugador"))
        self.pushButton_110.setText(_translate("MainWindow", "Jugador Nuevo"))
        self.pushButton.setText(_translate("MainWindow", "Atrás"))
        self.pushButton_2.setText(_translate("MainWindow", "Iniciar Partida"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())